# Copyright 2026 Duatic AG
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions, and
#    the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions, and
#    the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""Markdown report generation for the Duatic DynaArm operator tests."""

import os
from datetime import datetime

from duatic_dynaarm_testing.models import Session, TestResult
from duatic_dynaarm_testing.suites import ALL_SUITES


def _label(step_type) -> str:
    """Return the report label for a step type."""

    return getattr(step_type, "value", str(step_type)).upper()


def _escape(value: str) -> str:
    """Escape Markdown table separators and line breaks."""

    return value.replace("|", "\\|").replace("\n", "<br>")


def _format_test(result: TestResult) -> str:
    """Format one test result as a Markdown subsection."""

    lines = [
        f"### Test {result.id}: {result.name} - {result.status}",
        f"_{result.timestamp.strftime('%H:%M:%S')}_",
        "",
        "| Step | Type | Response |",
        "|------|------|----------|",
    ]
    for step in result.steps:
        lines.append(
            f"| {_escape(step.prompt)} | {_label(step.step_type)} | {_escape(step.response)} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_report(session: Session, overall: str) -> str:
    """Build the full Markdown report for a completed or partial session."""

    end_time = datetime.now()
    suite_names = {str(index): suite.name for index, suite in enumerate(ALL_SUITES, start=1)}
    suite_results: dict[str, list[TestResult]] = {}
    suite_order: list[str] = []
    for result in session.results:
        suite_id = result.id.split(".")[0]
        if suite_id not in suite_results:
            suite_results[suite_id] = []
            suite_order.append(suite_id)
        suite_results[suite_id].append(result)

    lines = [
        "# Duatic DynaArm Functional Safety Test Report",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Date | {session.start_time.strftime('%Y-%m-%d %H:%M:%S')} |",
        f"| Operator | {_escape(session.operator)} |",
        f"| Robot / System ID | {_escape(session.robot_id)} |",
        f"| Arm Version | {_escape(session.arm_version)} |",
        f"| EtherCAT Bus | {_escape(session.ethercat_bus)} |",
        f"| Overall Result | **{overall}** |",
        "",
        "---",
        "",
    ]

    for suite_id in suite_order:
        lines.append(f"## Suite {suite_id}: {suite_names.get(suite_id, f'Suite {suite_id}')}")
        lines.append("")
        for result in suite_results[suite_id]:
            lines.append(_format_test(result))

    lines.extend(
        [
            "---",
            f"_Report generated by duatic_dynaarm_testing on {end_time.strftime('%Y-%m-%d %H:%M:%S')}_",
        ]
    )
    return "\n".join(lines)


def write_report(session: Session, overall: str) -> str:
    """Write the Markdown report to the session output directory."""

    content = generate_report(session, overall)
    directory = os.path.expanduser(session.output_path)
    os.makedirs(directory, exist_ok=True)
    filename = f"dynaarm_test_report_{session.start_time.strftime('%Y%m%d_%H%M%S')}.md"
    path = os.path.join(directory, filename)
    with open(path, "w", encoding="utf-8") as report_file:
        report_file.write(content)
    print(f"\n[SYSTEM] Report written to: {path}")
    return path
