shoulder_rotation:
  max_joint_velocity: 10.64
  max_joint_effort: 120.0
shoulder_flexion:
  max_joint_velocity: 10.64
  max_joint_effort: 120.0
elbow_flexion:
  max_joint_velocity: 10.64
  max_joint_effort: 120.0
forearm_rotation:
  max_joint_velocity: 13.647
  max_joint_effort: 40.0
wrist_flexion:
  max_joint_velocity: 13.647
  max_joint_effort: 40.0
wrist_rotation:
  max_joint_velocity: 13.647
  max_joint_effort: 40.0
